### ISSUE TITLE
Make this compatible with Laravel 5.1

### ISSUE THREAD

**Issue by Konafets** [danielboendergaard/phantom-pdf#10]
I get the following error messsage:
```
[BadMethodCallException]
  Call to undefined method [package]
```

due the handling of packages was changed for 5.x https://github.com/laravel/framework/commit/3a0afc20f25ad3bed640ff1a14957f972d123cf7

**Comment by danielboendergaard** [comment]
There is a service provider for Laravel 5 included :)
https://github.com/danielboendergaard/phantom-pdf#laravel-5-installation-optional

**Comment by Konafets** [comment]
Ah, thank you for the hint.
