### ISSUE TITLE
Laravel 5.2

### ISSUE THREAD

**Issue by drahosistvan** [danielboendergaard/phantom-pdf#13]
The master branch is not working with Laravel 5.2, because of 2 main issues:
- Laravel 5.2 use 3.0.* version for `symfony/http-foundation` and `symfony/process` packages
- the `url()` function without any parameter is an instance of `Illuminate\Routing\UrlGenerator::class`, and the PdfGenerator class will fail

[Check my modifications](https://github.com/danielboendergaard/phantom-pdf/compare/master...drahosistvan:laravel52?diff=unified&name=laravel52). I did basic tests on OSX, and it worked.

**Comment by danielboendergaard** [comment]
I've pushed up your suggested changes at `0.10.0`
Thank you for letting me know and helping with the fixes :)
