### ISSUE TITLE
Unable to find generate-pdf.js when running this in Homestead(vagrant)

### ISSUE THREAD

**Issue by abodnar** [danielboendergaard/phantom-pdf#15]
I recently installed your package and when testing out how to use it, I wrote a quick view and unit test and when I execute the test in Homestead, I get this error:

`
Symfony\Component\Process\Exception\RuntimeException: PhantomJS: sh: 1: generate-pdf.js: not found

/home/vagrant/project/vendor/danielboendergaard/phantom-pdf/src/PdfGenerator.php:140
/home/vagrant/project/vendor/danielboendergaard/phantom-pdf/src/PdfGenerator.php:82
/home/vagrant/project/tests/PdfTest.php:18
`

My test is this:

`
namespace PdfTest.php;

use PhantomPdf\PdfGenerator;
use View;

class PdfTest.php extends \TestCase
{
    function testGeneratePdf()
    {
        $view = View::make('pdf.test');

        $pdf = new PdfGenerator();
        $pdf->setStoragePath('/tmp');

        $pdf->saveFromView($view, '/tmp/document.pdf');
    }
}
`

If i set the binary path to my Homebrew version of phantomjs and run the unit test locally, that works fine.

Thoughts?

**Comment by danielboendergaard** [comment]
Does it work if you set the script with the full path?

`$pdf->useScript('fullPath')`

**Comment by abodnar** [comment]
I added this to my test,
`
        $pdf->useScript(base_path() . '/vendor/danielboendergaard/phantom-pdf/src/generate-pdf.js');
`

and now I get:

1) CompetitiveSummaryTest\CompetitiveSummaryTest::testGeneratePdf
Symfony\Component\Process\Exception\RuntimeException: PhantomJS: sh: 1: /home/vagrant/project/vendor/danielboendergaard/phantom-pdf/src/generate-pdf.js: Permission denied

**Comment by danielboendergaard** [comment]
I just updated the package to `v1.0.0` try to update and use it without setting anything other than the storage path

**Comment by abodnar** [comment]
That seemed to resolve it. Thanks for fixing this!
