### ISSUE TITLE
base_url set in config does not do anything

### ISSUE THREAD

**Issue by abodnar** [danielboendergaard/phantom-pdf#16]
When I set the base_url in my config file it does not appear to create a base tag in the view or have any effect on the document.

**Comment by danielboendergaard** [comment]
Did you register the service provider?
https://github.com/danielboendergaard/phantom-pdf#installation-1

**Comment by abodnar** [comment]
Yes

PhantomPdf\Laravel\LaravelServiceProvider::class,

**Comment by danielboendergaard** [comment]
I haven't been able to recreate this. The code that inserts the base tag is pretty simple and I can't really see it failing:
````php
return str_replace('<head>', '<head><base href="'.$this->baseUrl.'">', $view);
````

**Comment by abodnar** [comment]
So it looks like my config is not being read as I was trying to debug an instance why the PDF I'm generating isn't getting some included css/JS files in the view despite setting --ssl-protocol=any in the phantom-pdf config file.

When I dd my pdf object after doing new PdfGenerator(), this is what I see.

PhantomPdf\PdfGenerator {#7
  #baseUrl: null
  #binaryPath: null
  #storagePath: null
  #htmlPath: null
  #pdfPath: null
  #timeout: 10
  #commandLineOptions: []
  #convertScript: "generate-pdf.js"
}

I also had the generated command output to a log and it didn't include the command line options either.

/home/vagrant/project/vendor/danielboendergaard/phantom-pdf/src/../bin/phantomjs  generate-pdf.js /home/vagrant/project/storage/app/pdf-572b87a6df2332.93345145.html /home/vagrant/project/storage/app/html-572b87a6df23a5.23616075.pdf

Obviously I can set it thru a object method, but it'd be nice to set it thru the config.

**Comment by danielboendergaard** [comment]
How do you instantiate the PdfGenerator class? For the config to work, you have to instantiate it via the IoC container either via injection or `app(PdfGenerator::class)`

**Comment by abodnar** [comment]
I'm just doing `$pdf = new PdfGenerator();` in a method of my class.

Do you have an example of where you do it with the IoC container?

**Comment by danielboendergaard** [comment]
Just do `$pdf = app(PdfGenerator::class);` or typehint it on your controller:
````php
public function foo(PdfGenerator $pdf)
  {
    return $pdf->createFromView(view('path'), 'filename.pdf');
  }
````

**Comment by abodnar** [comment]
That worked, thanks!
