### ISSUE TITLE
PDFGenerator Runtime Issue

### ISSUE THREAD

**Issue by zahidaziz16** [danielboendergaard/phantom-pdf#17]
Hi 
I receive this error after finish setup the package. I wanna try to view one web view in pdf, but I receive 

RuntimeException in PdfGenerator.php line 132:
PhantomJS: 'C:\xampp\htdocs\eiqa\vendor\danielboendergaard\phantom-pdf\src\config/../../bin/phantomjs' is not recognized as an internal or external command,
operable program or batch file.

Please help here.

**Comment by danielboendergaard** [comment]
You have to download the windows version of phantomjs and point to it in the config here:
https://github.com/danielboendergaard/phantom-pdf/blob/master/src/config/config.php#L51
