### ISSUE TITLE
Hyperlinks do not render as expected

### ISSUE THREAD

**Issue by jvalentinei** [danielboendergaard/phantom-pdf#19]
Hello, I'm running into an issue where rendering a Laravel view into a PDF works fine, except for hyperlinks. Here's my blade code:

`<h3><a href="http://www.google.com">Google</a></h3>`

And I will attach a screenshot. 

![screen shot 2016-08-02 at 15 53 47](https://cloud.githubusercontent.com/assets/8094805/17346094/c9e79d56-58ce-11e6-8da4-94dfdf76917d.png)

I get the text of the link underlined but unclickable, followed by the url which is clickable.

The desired result is a normal web hyperlink where the text of the link is clickable and the url is not visible.

I did some searching online and in the documentation, but couldn't find an answer.

**Comment by danielboendergaard** [comment]
This happens because the pdf is generated using the print media in css. Try to render the view normally and press print in the browser.

**Comment by jvalentinei** [comment]
The desired result I'm looking for is a link in a pdf file that is clickable like a normal link, so printing isn't part of my question.

I will work with style sheets specifically around using print media to see if I can get the desired result. Thanks much for the quick feedback. I will update as soon as I can.

**Comment by jvalentinei** [comment]
Found a solution that works:
- upgrade to phantomjs 2.1.11
- add this to the stylesheet:

@media print
 {
        a[href]:after {
            content: '';
        }
}
