### ISSUE TITLE
Process timing out but equivalent phantomjs command works fine

### ISSUE THREAD

**Issue by Harrisonbro** [danielboendergaard/phantom-pdf#20]
I've got phantom-pdf on a website that's been working mostly fine for some time but after our last deployment PDFs have stopped generating. We're getting this error:

```
1/1 in vendor/symfony/process/Process.php:1152 "The process "/path_to_application/vendor/bin/phantomjs /path_to_application/resources/assets/pdfConverter.js /path_to_application/storage/pdf-57a1daa85e7bd4.22475353.html /path_to_application/storage/html-57a1daa85e7c83.29019197.pdf" exceeded the timeout of 10 seconds."
```

Strangely enough, running the exact same command that the error shows on the command line works, suggesting maybe that the problem isn't with phantomJS itself? Note that when I try to generate the PDF through the web application the temporary HTML file is created but a PDF file is not (so phantomJS doesn't get that far).

Do you have any suggestions of where I could start looking to debug this?

**Comment by Harrisonbro** [comment]
Sorry, I found the problem: `selinux` was causing issues such that the `phantomjs` binary installed in `vendor/danielboendergaard/phantom-pdf/bin/phantomjs` couldn't create the PDF files.

**Comment by henrioseptiano** [comment]
Hi. I am just wondering that I had the same Issues like this on Windows 10. I already put the setBinaryPath methods as like this : $pdf->setBinaryPath('F:\phantomjs\phantomjs-2.1.1-windows\bin\phantomjs.exe');
can you tell me how to fix it up? my full code is actually like this:

 public function testpdf(PdfGenerator $pdf){
        
        $pdf->setBinaryPath('F:\phantomjs\phantomjs-2.1.1-windows\bin\phantomjs.exe');
        return $pdf->createFromView(view('report.pdf'), base_path().'public/screenshots/filename.pdf');
        
    }

**Comment by danielboendergaard** [comment]
@henrioseptiano Sorry for the late response. I haven't tried using it on windows, Try changing this line https://github.com/danielboendergaard/phantom-pdf/blob/master/src/PdfGenerator.php#L131 to `$process->getOutput()` instead of `$process->getErrorOutput()` to get the output from PhantomJS. Maybe that could show what is causing the error.
