### ISSUE TITLE
Pdf not generated until maximum execution time exceeded

### ISSUE THREAD

**Issue by Kunoacc** [danielboendergaard/phantom-pdf#21]
In laravel 5.4 on windows the pdf generates but not until the maximum execution set timeout is reached. Why does that happen and how do i rectify it?

**Comment by kurganskiy** [comment]
I have same problem and don`t know how to resolve it. I change view file content to simple <p>Привет</p>
and now i have another problem. I can`t open generated pdf :(  File type plain text document (text/plain) is not supported

**Comment by danielboendergaard** [comment]
I'm using this package myself om multiple Laravel 5.4 projects without issues. Maybe it's a symfony/process related issue

**Comment by Kunoacc** [comment]
How can it be resolved
Or show a sample of how you used it without issues

**Comment by danielboendergaard** [comment]
I just created a new Laravel 5.4 app and followed the instructions here without any issues at all: https://github.com/danielboendergaard/phantom-pdf#laravel-integration

Routes:
````php
<?php

Route::get('/', 'HomeController@index');
````

Controller
````php
<?php

namespace App\Http\Controllers;

use PhantomPdf\PdfGenerator;

class HomeController
{
    public function index(PdfGenerator $pdf)
    {
        $view = view('welcome');
        return $pdf->createFromView($view, 'test.pdf');
    }
}
````

**Comment by Kunoacc** [comment]
I am having this issue on windows and i think it has to do with JavaScript being asynchronous

**Comment by Kunoacc** [comment]
This didn't work for me
I am using it on windows as i forgot to mention that previously.
might that be the issue?

**Comment by danielboendergaard** [comment]
Have you downloaded the windows version of PhantomJS and referenced it like described here: https://github.com/danielboendergaard/phantom-pdf#phantomjs-version

**Comment by Kunoacc** [comment]
Yes i have
I've also linked the binaries 
And it still waits to timeout before it generates the pdf

**Comment by Kunoacc** [comment]
![capture](https://cloud.githubusercontent.com/assets/16244990/24643675/626ab272-1907-11e7-96a3-40f985df8c6a.PNG)
This is my code block where i use the pdfgenerator. It works fine but only after max execution time out as seen below:
![folder-before](https://cloud.githubusercontent.com/assets/16244990/24643709/931a97f2-1907-11e7-95d4-21bd94f67849.PNG)
This is my folder before the pdf is attempted top generate
![error](https://cloud.githubusercontent.com/assets/16244990/24643725/a95d5ed2-1907-11e7-9d62-e7f3d893638d.PNG)
and when i try to generate i get this(ignore the 5 second timeout. when i changed it to a second the pdf still generated fine) 
![folder-after](https://cloud.githubusercontent.com/assets/16244990/24643754/ca221a5e-1907-11e7-9074-fa09a9d14946.PNG)
but this is my folder after i get the error
![phpartisan_console](https://cloud.githubusercontent.com/assets/16244990/24643767/dc92d4d0-1907-11e7-8319-88bd7daf6892.PNG)
and this is my phpstorm terminal proving me right that the pdf generator only works after the error is thrown

**Comment by danielboendergaard** [comment]
This is definitely a symfony/process windows related problem, I don't think I can be of much help unfortunately :/
