### ISSUE TITLE
Images are not displayed in the pdf 

### ISSUE THREAD

**Issue by malaymehta** [danielboendergaard/phantom-pdf#23]
I am using this package for one of my project and it is working great. The only thing, that the image is not visible on the pdf file generated. Is that not the feature of this package or need to add something else for this?

Can you please help me with this?

**Comment by malaymehta** [comment]
My project is in laravel 5.5. So no need to use that.
use PhantomPdf\PdfGenerator;
$pdf = new PdfGenerator;
$pdf->setBinaryPath(env('PHANTOMJS_PATH'));
$pdf->setStoragePath(storage_path({my-storage-path}));
$pdf->saveFromView(view({my-view-name}, $data), $pdf_path);

My view file contains a block where I want to display the logo of the client company. $pdf_path is the variable - which has the path for the files stored.

Let me know if you need any more info.

**Comment by danielboendergaard** [comment]
Try this:

````php
$pdf->setBaseUrl(url('/'));
````

**Comment by malaymehta** [comment]
Ok, I will try it now and let you know.

**Comment by malaymehta** [comment]
Hi Daniel, I checked and found that it works and generate correctly in the Windows Installation, but it does not work correctly on the Ubuntu system where the production site is hosted. I tried in the view by giving the full-url and also giving the url like url('front/images/logo.png')

The same logic works in the windows but not in the linux. 

Windows PhantomJS version is: v2.1.1
Linux PhantomJS version: 2.1.1

**Comment by danielboendergaard** [comment]
I make my urls relative to the public folder like this:

````html
<img src="/img/filename.png">
````

**Comment by malaymehta** [comment]
Let me try this.

**Comment by malaymehta** [comment]
I tried, but still I cannot see the image in the pdf file.

**Comment by danielboendergaard** [comment]
Ok, I'm not sure I can help you then.  Maybe try this instead which uses Chrome to create the pdf https://github.com/spatie/browsershot it does require you to install some software though.

**Comment by malaymehta** [comment]
Thanks for the help, Daniel. The issue is resolved. I had to add some proper timeout and set the image path in some different way.
