### ISSUE TITLE
CSS not loading over https

### ISSUE THREAD

**Issue by tasosback** [danielboendergaard/phantom-pdf#26]
I have a laravel 5 site that was running in http but since they turned it to Https the css is not loading. The view produced is ok as i can see but the pdf does not have any styling (probably the css is not loaded). I see some previous issues that were solved. Where do i add the --ignore-ssl-errors=true setting?

**Comment by danielboendergaard** [comment]
Publish the config file by running `php artisan vendor:publish`
In the published config file, uncomment this line https://github.com/danielboendergaard/phantom-pdf/blob/master/src/config/config.php#L77

**Comment by tasosback** [comment]
First of all thanks for the reply. I already changed the published config file "app/config/packages/danielboendergaard/phantom-pdf/config.php" and commented out the line you specified but it did not work. If I run php artisan vendor:publish will it affect other packages as well? is it necessary to run it if I already changed the published config file?

**Comment by tasosback** [comment]
Actually I made a simple test without https and still the css styling is ignored. Only inline styles work. Can this be a version issue? What version do you recommend for Laravel 5?

**Comment by danielboendergaard** [comment]
Try setting the base_url here: https://github.com/danielboendergaard/phantom-pdf/blob/master/src/config/config.php#L27

**Comment by tasosback** [comment]
Changed the base url but it did not work.

**Comment by tasosback** [comment]
Any other ideas? Does the library support css files at all?

**Comment by danielboendergaard** [comment]
The url used in the link tag must be reachable from the host machine itself. This can cause dns and https issues. It's probably easier to inline the css.

Alternatively I would take a look at one of these options:
https://packagist.org/packages/barryvdh/laravel-dompdf
https://packagist.org/packages/spatie/browsershot
