### ISSUE TITLE
ignore-ssl-errors doesn't work ?

### ISSUE THREAD

**Issue by cilyaa** [danielboendergaard/phantom-pdf#5]
Hi,

I've had some problems with loading assets (css / js) on PDF generation on a staging server. (Note that this might be related to / a duplicate of #4, but i'm not certain).

The staging server uses auto-signed certificate for HTTPS. However, setting ``ignore-ssl-errors`` to true didn't work this time (it indeed worked in the past on other Laravel 4 projects...).

After investigation, i've finally made a breakthrough after reading this thread : https://github.com/ariya/phantomjs/issues/12181

When turning the ``debug`` on in the phantomJS CLI call, the output contained the "SSL handshake failed" errors. Adding the protocol option (eg. ``--ssl-protocol=tlsv1``) in the CLI solved my issue (for the time being).

Although it doesn't seem to fix the problem in the long run, and doesn't work for everyone, it might be useful to expose more CLI options in the config file (at least ``debug`` and ``ssl-protocol``, i'd say).

Thanks !

**Comment by danielboendergaard** [comment]
Thanks for your feedback! I just pushed https://github.com/danielboendergaard/phantom-pdf/commit/311cc5d97c1066f4dde5872fa9618b9f98f738f4 which adds a config option for command line options.

**Comment by cilyaa** [comment]
As usual, works like a charm :+1: 

thanks a lot !
