### ISSUE TITLE
add a js file path option to the config

### ISSUE THREAD

**Issue by cilyaa** [danielboendergaard/phantom-pdf#6]
Hi, 

I've had the case recently where I needed to hack the `generate-pdf.js` script. However, when the package will be updated, thoses hacks will be, as intended by composer, lost. 
As such, I'd love to have an option in the config file where one could indicate his own js script for phantomjs.

What are your thoughts on this ?

Kind regards :)

**Comment by danielboendergaard** [comment]
I'll add a method to set a custom script since you might want to use different scripts in the same application. I will probably have time to do it tomorrow :)

**Comment by danielboendergaard** [comment]
I added a `useScript('path_to_script')` method in 0.6.2, i hope it solves your use case

**Comment by cilyaa** [comment]
Ahh, sorry for the delay in my response... I've got completely sidetracked by other ongoing projects.

I've tested `useScript` and it works nicely :)

Thanks a lot !
