### ISSUE TITLE
Windows & phantomjs 2.0 issue

### ISSUE THREAD

**Issue by acasar** [danielboendergaard/phantom-pdf#9]
I noticed an issue when using this package with Windows and phantomjs 2.0.

The command it generates is:

```
C:\phantomjs\bin\phantomjs.exe generate-pdf.js C:\xampp\htdocs\project\storage\pdf-55e22f9a732416.83117326.html C:\xampp\htdocs\project\storage\html-55e22f9a732638.09310424.pdf
```

But it fails to open the source file. I managed to fix it by prefixing the source path with file:/// like so:

```
C:\phantomjs\bin\phantomjs.exe generate-pdf.js file:///C:\xampp\htdocs\project\storage\pdf-55e22f9a732416.83117326.html C:\xampp\htdocs\project\storage\html-55e22f9a732638.09310424.pdf
```

It seems that a well-formatted URL is expected as a first argument. Do you think you could include that change in the package? I can also submit a pull request.

**Comment by danielboendergaard** [comment]
Sorry for the late response but try out version `0.9.0` :)

**Comment by acasar** [comment]
@danielboendergaard Thanks a lot :)
